#!/bin/bash
set -o nounset

# Get the IDs of VPC, Route table, subnet, internet gateway, and security group from state_file.txt

source state_file.txt

# Print the Details of VPC
echo "VPC Details:"
aws ec2 describe-vpcs --vpc-ids $vpc_id

# Print the Details of Routing Table
echo "Routing Table Details:"
aws ec2 describe-route-tables --route-table-ids $route_table_id

# Print the Details of Subnet
echo "Subnet Details:"
aws ec2 describe-subnets --subnet-ids $subnet_id

# Print the Details of Internet Gateway
echo "Internet Gateway Details:"
aws ec2 describe-internet-gateways --internet-gateway-ids $gateway_id

# Print the Details of Security Group
echo "Security Group Details:"
aws ec2 describe-security-groups --group-ids $security_group_id
